### ISSUE TITLE
TypeError: Invalid RFC-3339 date-time value when sending AssumeRoleWithWebIdentityCommand

### ISSUE THREAD

**Issue by cwang77** [aws/aws-sdk-js-v3#2866]
## Describe the bug
Got error `TypeError: Invalid RFC-3339 date-time value` when sending command `AssumeRoleWithWebIdentityCommand ` from `STSClient `. The network request itself is successful by checking the network debug tool in chrome. The error happens when the SDK trying to deserialize credentials expiration date from the http response. 

## Your environment
React web application that deployed to AWS S3 and using the endpoint created by AWS Cloudfront. The web identity  endpoint we are using is `https://midway-auth.amazon.com/SSO`

#### SDK version number
`@aws-sdk/client-sts@3.34.0`

#### Is the issue in the browser/Node.js/ReactNative?
Browser

#### Details of the browser/Node.js/ReactNative version
npx: installed 1 in 1.532s

  Browsers:
    Chrome: 94.0.4606.71

## Steps to reproduce
```
    const client = new STSClient({ region: 'us-west-2' });
    const command = new AssumeRoleWithWebIdentityCommand({
        RoleArn: DASHBOARD_ROLE_ARN,
        RoleSessionName: `${SESSION_PREFIX}${Date.now()}`,
        WebIdentityToken: token
    });
    client.send(command)
        .then(data => onAssumeRoleSuccessful(data, callback))
        .catch(error => callback(error));
```

#### Observed behavior
Once we have the web identity token. we are executing the above code in order to get the credentials. Due to the above code snippet,  the error will be caught and used as the argument in the callback function. In callback function, we print the error out.  See screenshot below.

#### Expected behavior
We should not get this error at all. Just an FYI, if we downgrade to SDK v2 and this issue will just gone. 

#### Screenshots
![Screen Shot 2021-10-02 at 12 51 20 AM](https://user-images.githubusercontent.com/4888641/135933828-f48ebf3e-a4ab-4b22-a719-ab72ca0efce6.png)

**Comment by slimandslam** [comment]
This seems like it might be a bug that was introduced in this version, or another recent version, or the library. Is there an earlier version of the library that works (as a temporary workaround)?

**Comment by slimandslam** [comment]
I set my aws-sdk components to version 3.20.0 and everything works again as expected. I'm not sure which version between 3.20.0 and 3.34.0 introduces the bug tho.  I have a feeling that version 3.35.0 still has the bug.

**Comment by Grendaizo90** [comment]
@mr-py-007 i made a new build, and now i have the same issue, and nothing works

**Comment by jamesaucode** [comment]
Looking through the source code, it seems like this is where the error is originating from.
https://github.com/aws/aws-sdk-js-v3/blame/main/packages/smithy-client/src/date-utils.ts#L66
For some reason in production build, the regex test is not passing hence it throws the `TypeError`

It seems like this is introduced in #2737 and is released for versions >=3.30. My builds run fine with `3.29.0`.

**Comment by JJSphar** [comment]
I'm seeing a similar error (#2977), when sending a request with `credentials` through the `S3Client` after upgrading to version 3.30.

The RFC standard being validated against is 7231, not 3339 - but the error is being thrown from the same commit that @jamesaucode linked, just a few lines further down.  It also is only an issue in Production builds.

Wanted to drop some thoughts here in case these are the same root cause.

**Comment by jamesaucode** [comment]
to add to @JJSphar 's post I was also experiencing this issue on `S3Client` with `ListObjectsCommand`

**Comment by slimandslam** [comment]
Anyone tried v3.40.0 yet?  https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.40.0
Allegedly, the problem is fixed but I don't see the change in the changelog nor the Github issues mentioned (#2977 and #2866)

**Comment by Grendaizo90** [comment]
@slimandslam i tried 3.40 right now (for S3Client) but the issue still persists

**Comment by Grendaizo90** [comment]
@AllanZhengYP i hope that you didn't forget about this issue :) because in v3.41.0 still no changes

**Comment by slimandslam** [comment]
Anyone tried v3.42.0 yet?

**Comment by slimandslam** [comment]
Anyone tried v3.44.0 yet?

**Comment by slimandslam** [comment]
Anyone tried v3.45.0 yet?

**Comment by slimandslam** [comment]
Anyone tried v3.46.0 or v3.47.0 yet?

**Comment by slimandslam** [comment]
Anyone tried v3.48.0 yet?

**Comment by slimandslam** [comment]
Anyone tried v3.50.0 yet?

**Comment by slimandslam** [comment]
Anyone tried v3.51 yet?

**Comment by slimandslam** [comment]
Anyone know if this is fixed yet?

Jason

**Comment by slimandslam** [comment]
Anyone tried v3.52 yet?

**Comment by slimandslam** [comment]
Anyone tried v3.53 yet?

**Comment by slimandslam** [comment]
Any fix yet @AllanZhengYP  ?

**Comment by AllanZhengYP** [comment]
@slimandslam  The same issue should be fixed in #2977 and related PR. This one might be a similar but slightly different issue with prod bundle of `Regex`. Reassigning this to @ajredniwja for reproduction and uglified code deep-dive.

**Comment by Ceres6** [comment]
This seems to be solved for most commands. However as of `v3.391.0` in the `s3-client` it keeps failing for list object commands both legacy an v2 versions. 

Is there any chance we can get this working? As it has been solved for so many other commands it should be a known solution.

I'd be glad to help if that's possible and someone can point me in the right direction.

**Comment by ntang86** [comment]
Hello, I'm using "@aws-sdk/client-pinpoint" v3.391.0, and I have the same error when creating a new Journey with `pinpoint.createJourney`, the request will return an error object without name

{"level":30,"time":1697486130297,"pid":97083,"hostname":"nt-local","reqId":"req-1","msg":"Journey init:"}
{"level":50,"time":1697486130720,"pid":97083,"hostname":"nt-local","reqId":"req-1","errorObject":{"$metadata":{"attempts":1,"totalRetryDelay":0}},"msg":"Something went wrong."}


<img width="1243" alt="Screenshot 2023-10-16 at 3 54 18 PM" src="https://github.com/aws/aws-sdk-js-v3/assets/138027010/4c7ef85a-14db-468c-94a8-9ddc9389c361">

This error occurs only when I try to change the timestamp with setUTCHours or setHours and other manipulation such as: 

```
new Date('October 16, 2023 17:00:00 GMT')
```

**Comment by RanVaknin** [comment]
Hi there,

There are multiple customers reporting issues on this thread. 
Seems like some of this is resolved. @Ceres6 if this is still an issue can you please pull the latest version of the SDK and if the issue persists open a new issue and supply all the reproduction info needed. 

@ntang86 same goes to you. if this is still an issue after pulling the latest version, please create a new separate issue since this error can manifest for many different reasons.

Thanks,
Ran~
