### ISSUE TITLE
S3 Client Segmentation Fault on Ubuntu

### ISSUE THREAD

**Issue by jameswestbv** [aws/aws-sdk-js-v3#3320]
## Describe the bug
When using the S3 Client in a Node JS  worker thread a seg fault occurs when exiting the thread when running on Ubuntu 20.04
(Example works as expected on Windows)

## Your environment
NodeJs 16.14.0
Ubuntu 20.04.3 LTS

#### SDK version number
`@aws-sdk/client-s3@3.46.0`

#### Is the issue in the browser/Node.js/ReactNative?
Node.js

#### Details of the browser/Node.js/ReactNative version
v16.14.0

## Steps to reproduce
```js
#!/usr/bin/env node

import { S3 } from '@aws-sdk/client-s3';
import { Worker, isMainThread, parentPort } from 'worker_threads';

if (isMainThread) {

	const worker = new Worker('./segfault.js');

	worker.on('message', (msg) => {
		console.log('Worker says: '+msg);
	});

	worker.on('exit', (code) => {
		console.log('Worker Thread exit');
	})

} else {
	
	// This code is executed in the worker and not in the main thread.

	async function doSomeWorkerWork() {
	
		let s3Client = new S3({
			endpoint: "https://ams3.digitaloceanspaces.com",
			region: "us-east-1",
			credentials: {
				accessKeyId: "doesn't matter for this test",
				secretAccessKey: "doesn't matter for this test"
			}
		});

		// Do something important with S3
		await new Promise(resolve => setTimeout(resolve, 1000));
		
		parentPort.postMessage('I\'m Done');
		
		s3Client.destroy();

		process.exit(0);

	}

	doSomeWorkerWork();

}
```

#### Observed behavior
When the thread exits it results in
`Segmentation Fault(core dumped) `

#### Expected behavior
Thread should exit gracefully as it does on Windows

#### Screenshots
Ubuntu:
![ubuntu](https://user-images.githubusercontent.com/6533453/154248853-82f1e625-11a9-4ba9-84cb-8f84d3b534d9.jpg)

Windows:
![windows](https://user-images.githubusercontent.com/6533453/154249430-1938861c-0460-41e5-95b4-54d8541b476a.jpg)

## Additional context
Removing the instantiation of the S3 client makes the seg fault go away.
The destroy() has no affect, tried it as it was recommended for node js

**Comment by Steffen911** [comment]
I get the same error and exit code if I use the `S3Client` inside of a `child_process`.

**Comment by AidanJHMurphy** [comment]
I just ran into the same bug on Ubuntu 20.04.4 with @aws-sdk/client-s3@3.54.0 and node v16.14.2. Very eager to see this fixed.

**Comment by jaw111** [comment]
I'm facing a similar issue using S3Client in a worker thread using AWS Lambda with latest Node.js 18.x runtime. I'd say it fails on roughly half the invocations of the function.

I see this error in the logs:

```
Error: Runtime exited with error: signal: segmentation fault
```

**Comment by yenfryherrerafeliz** [comment]
Hi @jameswestbv, thanks for opening this issue. I tried to reproduce this issue but I could not. 
What I did was the following:
- I installed node:
    - ``` sudo apt update ```
    - ``` sudo apt upgrade ```
    - If curl is not installed ``` sudo apt install -y curl ```
    - ``` curl -fsSL https://deb.nodesource.com/setup_19.x | sudo -E bash - ```
    - ``` sudo apt install -y nodejs ```
- The steps above will install the version 19.x of node, however, to install the version you mentioned in specific I did the following:
    - ``` sudo npm cache clean -f ```
    - ``` sudo npm install -g n ```
    - ``` sudo n 16.14.0 ```
- Then, I created a node project as follow:
    - ``` npm init ```
    - ``` create a js file. Example: src/index.js ```
    - Install the used dependencies: ``` npm i @aws-sdk/client-s3 ```
    - Copy and paste the code below:
    ```js
    #!/usr/bin/env node
    
    import {
        Worker, isMainThread, parentPort
    } from "worker_threads";
    import {ListBucketsCommand, S3Client} from "@aws-sdk/client-s3";
    
    if (isMainThread) {
        const worker = new Worker('./index.js');
        worker.on('message', (msg) => {
            console.log('Worker message: ', msg)
        })
    
        worker.on('exit', (code) => {
            console.log('Exit because: ', code)
        })
    
        worker.on('error', (error) => {
            console.log('Error: ', error)
        })
    } else {
        const doWork = async () => {
            const client = new S3Client({
                region: 'us-east-2',
                credentials: {
                    accessKeyId: 'accesskeyId',
                    secretAccessKey: 'secretAccessKey'
                }
            })
            const response = await client.send(new ListBucketsCommand({}));
            console.log(response)
            parentPort.postMessage('I am done!')
            client.destroy()
            process.exit(0)
        }
    
        await doWork();
    }
    ```

So, is there any other detail I should consider to reproduce the error?

@Steffen911, @Coniface, @AidanJHMurphy, and @jaw111, would it be possible for any of you to provide reproduction steps based on your implementation?

Thanks!

**Comment by yenfryherrerafeliz** [comment]
Could you people also confirm if you have two installations of node?, you could confirm that by running ``` nodejs -v ``` and ``` node -v ``` and check if for both commands you get a result?

Thanks!

**Comment by jameswestbv** [comment]
@yenfryherrerafeliz 

Looks like it has been fixed at some point in the last year between version 3.46.0 --> 3.252.0

If you really want to reproduce it you would need the latest version from Feb 2022 when I raised this which is `npm i @aws-sdk/client-s3@3.46.0`

But as it looks like its fixed in the later versions then there isn't much more to add.

**Comment by jaw111** [comment]
@yenfryherrerafeliz I'm using the Node.js 18.x runtime for AWS Lambda. If it is useful/necessary to reproduce the bug in Lambda, I could provide some minimal code that demonstrates the issue, but it would also require the necessary AWS infrastructure to run it. Do you have any suggestions how to go about that?

**Comment by yenfryherrerafeliz** [comment]
Hi @jaw111, thanks for replying back. Would it be possible for you to check if with the latest version the issue persist?

Thanks!
