### ISSUE TITLE
3.192.0 introduces breaking change: Cannot find module '@aws-sdk/util-endpoints'

### ISSUE THREAD

**Issue by thetutlage** [aws/aws-sdk-js-v3#4060]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

This commit https://github.com/aws/aws-sdk-js-v3/commit/6e4371eade7c2da3e3a930e1a14a52c88af8ad54#diff-2c9b50a7c5201e808afb3f485a693f85389fbeef01b9282a5a31dcd325fffb2aR40 has introduced a breaking change by removing `@aws-sdk/util-endpoints`. However, the module is still in use in this file https://github.com/aws/aws-sdk-js-v3/commit/6e4371eade7c2da3e3a930e1a14a52c88af8ad54#diff-6ba586ec001f1ef54aa2387edbec307279cb4e6e815c4af3433dc3eb3fa9a095R3

### SDK version number

@aws-sdk/client-s3@3.192.0

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

16.18.0

### Reproduction Steps

Just install `@aws-sdk/client-s3@3.192.0` and you will be able to reproduce this

### Observed Behavior

Breaks

### Expected Behavior

Should not break.

**Comment by sandrooco** [comment]
A bit more context:

```
Error: Cannot find module '@aws-sdk/util-endpoints'
Require stack:
- /Users/.../node_modules/@aws-sdk/client-s3/dist-cjs/endpoint/endpointResolver.js
- /Users/.../node_modules/@aws-sdk/client-s3/dist-cjs/runtimeConfig.shared.js
- /Users/.../node_modules/@aws-sdk/client-s3/dist-cjs/runtimeConfig.js
- /Users/.../node_modules/@aws-sdk/client-s3/dist-cjs/S3Client.js
- /Users/.../node_modules/@aws-sdk/client-s3/dist-cjs/S3.js
- /Users/.../node_modules/@aws-sdk/client-s3/dist-cjs/index.js
- /Users/.../project-folder/dist/s3-file/s3-connector.service.js
```

@thetutlage maybe you want to update the title to something like: "3.192.0 introduces breaking change: Cannot find module '@aws-sdk/util-endpoints'"

**Comment by arvindnarang1i11y** [comment]
facing same issue, a breaking change for all who are using latest minor versions in package.json I guess. hoping this gets fixed soon. OP - If you could please edit the title to be more precise , It might help with getting right amount of attention asap.

**Comment by sam-frampton** [comment]
Facing same issue as well, +1 on getting fixed soon.

**Comment by masoomikea** [comment]
Having the same issue from morning. Hopefully it will be fixed soon.

**Comment by futin** [comment]
Having the same issue as well.

**Comment by rnkdsh** [comment]
Same issue

**Comment by MElkady** [comment]
Getting the same issue with version 3.192.0

**Comment by sandrooco** [comment]
**This easily fixable when going back to 3.190.0.**

For those that never heard this before: posting "same" doesn't really help contributors. Please provide additional debugging information if possible (although not really needed here). You can also subscribe to the issue and use emoji reactions on the top post to show maintainers the importance of the issue.

In case you have "latest" in your package.json: consider using something like [Renovate](https://github.com/renovatebot/renovate) to update your packages. It will create branches with the updated versions, so you will be notified that something broke before having it on your main branches.

**Comment by rnkdsh** [comment]
Temporary workaround is to install `@aws-sdk/util-endpoints` manually using `npm install @aws-sdk/util-endpoints`

**Comment by jpalacio1988** [comment]
Same issues

**Comment by hackmajoris** [comment]
Same issue

**Comment by jpalacio1988** [comment]
I maked the rollback to version 3.190.0 and works temporarily

"@aws-sdk/client-kms": "3.190.0",
"@aws-sdk/client-rekognition": "3.190.0",
"@aws-sdk/client-s3": "3.190.0",
"@aws-sdk/client-sqs": "3.190.0",
"@aws-sdk/client-ssm": "3.190.0",
"@aws-sdk/client-textract": "3.190.0",

**Comment by jeremy-brooks** [comment]
Alternatively, just including the utils module separately works with the latest version of the sdk for example:

```
"@aws-sdk/client-s3": "^3.192.0",
"@aws-sdk/util-endpoints": "^3.192.0"
```

**Comment by sagar7993** [comment]
Same issue

**Comment by HebertMedeloAdl** [comment]
```
"@aws-sdk/client-s3": "^3.192.0",
"@aws-sdk/util-endpoints": "^3.192.0"
```
Así funciono

**Comment by gwdp** [comment]
#4058 seems to be the fix for it.. waiting for the next release to be fixed, I guess.
I would encourage a release ASAP if the team is reading this.

**Comment by xinaxu** [comment]
I managed to mitigate this issue by downgrading the npm

**Comment by bRRRITSCOLDtkww** [comment]
Same issue - looking at workaround

**Comment by jaqarrick** [comment]
Same issue

**Comment by scottmanny** [comment]
This is what I did to get it working.
```
.
.
."dependencies": {
    .
    .
    "@aws-sdk/client-s3": "3.190.0",
    "@aws-sdk/util-endpoints": "3.190.0",
    .
    .
},
.
.
.
"resolutions": {
    "@aws-sdk/client-s3": "3.190.0",
    "@aws-sdk/util-endpoints": "3.190.0"
  },
```

**Comment by slikk66** [comment]
Yep - broke my app just now with:
`"aws-sdk": "^2.1036.0",` as the only entrance into aws packages.

Fixed it by combing through logs and adding:
`"@aws-sdk/util-endpoints": "^3.192.0",`

**Comment by Teja21780** [comment]
> "resolutions": {
>     "@aws-sdk/client-s3": "3.190.0",
>     "@aws-sdk/util-endpoints": "3.190.0"
>   },

Tried this, it did not work for me

**Comment by jsmith213561** [comment]
I experienced the same issue in [734](https://github.com/awslabs/aws-mobile-appsync-sdk-js/issues/734) but the above solutions aren't working for me

**Comment by trivikr** [comment]
Already fixed, and will be released with `v3.193.0` today. Marking as duplicate.

Check out details in https://github.com/aws/aws-sdk-js-v3/issues/4053

**Comment by trivikr** [comment]
This issue is fixed in `v3.193.0`

<details>
<summary>Source code</summary>

```mjs
import { S3 } from "@aws-sdk/client-s3";

const client = new S3({});
console.log(await client.listBuckets({ Limit: 1 }));
```

</details>

<details>
<summary>Cannot find module error with @aws-sdk/client-s3@3.192.0</summary>

```console
node:internal/modules/cjs/loader:985
  const err = new Error(message);
              ^

Error: Cannot find module '@aws-sdk/util-endpoints'
Require stack:
- /Users/trivikr/workspace/test/node_modules/@aws-sdk/client-s3/dist-cjs/endpoint/endpointResolver.js
- /Users/trivikr/workspace/test/node_modules/@aws-sdk/client-s3/dist-cjs/runtimeConfig.shared.js
- /Users/trivikr/workspace/test/node_modules/@aws-sdk/client-s3/dist-cjs/runtimeConfig.js
- /Users/trivikr/workspace/test/node_modules/@aws-sdk/client-s3/dist-cjs/S3Client.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:985:15)
    at Function.Module._load (node:internal/modules/cjs/loader:833:27)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/trivikr/workspace/test/node_modules/@aws-sdk/client-s3/dist-cjs/endpoint/endpointResolver.js:4:26)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/trivikr/workspace/test/node_modules/@aws-sdk/client-s3/dist-cjs/endpoint/endpointResolver.js',
    '/Users/trivikr/workspace/test/node_modules/@aws-sdk/client-s3/dist-cjs/runtimeConfig.shared.js',
    '/Users/trivikr/workspace/test/node_modules/@aws-sdk/client-s3/dist-cjs/runtimeConfig.js',
    '/Users/trivikr/workspace/test/node_modules/@aws-sdk/client-s3/dist-cjs/S3Client.js'
  ]
}
```

</details>

<details>
<summary>No error with @aws-sdk/client-s3@3.193.0</summary>

```console
{
  '$metadata': {
    // Redacted
  },
  Buckets: [
    // Redacted
  ],
  Owner: {
    // Redacted
  }
}
```

</details>

**Comment by SyedAsimAliSE** [comment]
> 

Hi @trivikr thanks for fixing it , but we are still getting these warnings in our builds

![image](https://user-images.githubusercontent.com/44644354/197061594-59908027-4a50-41f2-8579-1e26597765f0.png)
![image](https://user-images.githubusercontent.com/44644354/197061777-463f3eab-daec-498f-8145-99aad77df371.png)

**Comment by chuckntaylor** [comment]
@trivikr I know pretty much everyone ran into this problem with `@aws-sdk/client-s3` — and I too had this come up for me last night on a project, but I had remedied it by installing `@aws-sdk/utils-endpoints` separately. I just wanted to bring attention to this also being an issue with `amazon-chime-sdk-js 3.8.0`. Again, I have solved it by just installing utils-endpoints separately. As the merged solution above only mentions client-s3, I thought I'd let you know.

**Comment by sali141** [comment]
> > 
> 
> Hi @trivikr thanks for fixing it , but we are still getting these warnings in our builds
> 
> ![image](https://user-images.githubusercontent.com/44644354/197061594-59908027-4a50-41f2-8579-1e26597765f0.png) ![image](https://user-images.githubusercontent.com/44644354/197061777-463f3eab-daec-498f-8145-99aad77df371.png)

I am having the same issue.. any update for bellow error 

`Attempted import error: 'partitions'.'find' is not exported from './partitions.json' (imported as 'partitions').
`

**Comment by sali141** [comment]
@trivikr 
I am having the same error as above . any idea how to fix it?

`Attempted import error: 'partitions'.'find' is not exported from './partitions.json' (imported as 'partitions').`

**Comment by jsmith213561** [comment]
@trivikr 

@sali141 is right we're still experiencing issue in our builds. Here is the snap from mine build of react app.
![image](https://user-images.githubusercontent.com/97633012/197215920-a72f52b5-cfe5-450c-a7cc-7a02228eb41f.png)

**Comment by jsmith213561** [comment]
`./node_modules/@aws-sdk/util-endpoints/dist-es/lib/index.js 1:9
                                 Module parse failed: Unexpected token (1:9)
                                 File was processed with these loaders:
                                 * ./node_modules/babel-loader/lib/index.js
                                 You may need an additional loader to handle the result of these loaders.
                                 > export * as aws from "./aws";
                                 | export * from "./booleanEquals";
                                 | export * from "./getAttr";
2022-10-20T14:02:30.704Z [WARNING]: npm
2022-10-20T14:02:30.704Z [WARNING]: ERR! code ELIFECYCLE
                                    npm ERR! errno 1
2022-10-20T14:02:30.706Z [WARNING]: npm
2022-10-20T14:02:30.706Z [WARNING]: ERR! PEGDashboard@0.1.0 build: "react-scripts build"`

**Comment by trivikr** [comment]
@SyedAsimAliSE  @sali141 

Please follow-up details in https://github.com/aws/aws-sdk-js-v3/issues/4067#issuecomment-1287253247
If you have a minimal repro code, please post it in that issue.

@jsmith213561

I suspect the error you're getting is because of the same cause as explained in https://github.com/aws/aws-sdk-js-v3/issues/4067#issuecomment-1287253247
If it's not, please create a new [bug report](https://github.com/aws/aws-sdk-js-v3/issues/new?assignees=&labels=bug%2Cneeds-triage&template=bug-report.yml&title=TITLE+FOR+BUG+REPORT) with a minimal repro.

@chuckntaylor

The issue you mentioned if with https://github.com/aws/amazon-chime-sdk-js
Please create a [bug report](https://github.com/aws/amazon-chime-sdk-js/issues/new?assignees=&labels=&template=bug-report.yaml) with Amazon Chime SDK repo. You can reference GitHub issues from AWS SDK for JavaScript repo there.

I'm locking this issue to prevent further noise. The bug discussed in this issue is already fixed and verified in https://github.com/aws/aws-sdk-js-v3/issues/4060#issuecomment-1286136274
