### ISSUE TITLE
NULL response body incorrectly treated as Uint8Array in `collectBody` method 

### ISSUE THREAD

**Issue by limzykenneth** [aws/aws-sdk-js-v3#4369]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

I'm not very familiar with the overall codebase but I've only track down the offending line so sorry in advanced for the lack of details below.

While trying to use the s3 client in a Cloudflare Workers environment with the `DeleteObjectCommand` I'm getting the following error message: `TypeError: stream.getReader is not a function` with an eventual trace to [this function](https://github.com/aws/aws-sdk-js-v3/blob/main/clients/client-s3/src/protocols/Aws_restXml.ts#L12015), and the problem is that the `streamBody` argument passed here should have defaulted to a blank `UInt8Array` when there is no body but further upstream in the stack trace, the body is set to `null` which does not trigger the default argument value and thus get passed along to `streamCollector` that eventually attempts to call `getReader` on `null`.

### SDK version number

@aws-sdk/client-s3@3.254.0

### Which JavaScript Runtime is this issue in?

Browser

### Details of the browser/Node.js/ReactNative version

Cloudflare Workers, wrangler@2.8.1

### Reproduction Steps

I'm not sure if running in Cloudflare workers are relevant or not in this case.

```
await client.deleteObject({
  Bucket: "my-bucket",
  Key: "filename"
});
```

### Observed Behavior

A more complete stack trace if it helps, although there's no useful line numbers I imagine:
```
TypeError: stream.getReader is not a function
    at collectStream ([...]/dist/worker.js:27440:27)
    at Object.streamCollector ([...]/dist/worker.js:27431:12)
    at collectBody ([...]/dist/worker.js:19480:20)
    at deserializeAws_restXmlDeleteObjectCommand ([...]/dist/worker.js:13067:11)
    at deserialize ([...]/dist/worker.js:20719:16)
    at [...]/dist/worker.js:6766:30
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at [...]/dist/worker.js:26571:20
    at [...]/dist/worker.js:25777:46
```

The delete object command still successfully deleted the object though.

### Expected Behavior

No errors to occur.

### Possible Solution

My current direct patch is as follow but I think maybe an upstream solution may be required? I'm not sure.

```js
const collectBody = (streamBody = new Uint8Array(), context) => {
    if (streamBody instanceof Uint8Array) {
        return Promise.resolve(streamBody);
    }else if (!streamBody){
        return Promise.resolve(new Uint8Array());
    }
    return context.streamCollector(streamBody) || Promise.resolve(new Uint8Array());
};
```

**Comment by yenfryherrerafeliz** [comment]
Hi @limzykenneth, thanks for opening this issue. I think it might be an issue that occurs when using CloudFlare in specific, because I am not able to reproduce it using nodejs runtime. I can not actually think on a scenario where the body of the response is null. Are you getting this issue every time you send a delete object command?, or does it happen sporadically?

I am not a CloudFlare expert but I am working on it to try to replica the issue on my end and find the best way to help you, so it will be really great if you can provide any other details you think will be useful to reproduce this issue.

Thanks!

**Comment by limzykenneth** [comment]
I'll try to make a minimal test case but just to clarify, it is not the **response** body is null but the **request** body is `null` (instead of `undefined`).

**Comment by limzykenneth** [comment]
I'll try to create a minimal test case.

**Comment by limzykenneth** [comment]
Here's the minimal test case: https://github.com/limzykenneth/cf-aws-test

To use you'll need to replace the key id and secret in `index.js` then run with `npx wrangler dev --local`.

**Comment by yenfryherrerafeliz** [comment]
The following [issue](https://github.com/aws/aws-sdk-js-v3/issues/4398) maybe related.

I am currently investigating this issue. We do not have this behavior when using nodejs so that I need to find out what exactly causes the issue when using cloudflare or other similar runtimes.

Thanks!

**Comment by hanzlahabib** [comment]
Thank you, @limzykenneth , I am also facing the same issue with Cloudflare workers,

**Comment by kuhe** [comment]
A fix was released in [v3.329.0](https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.329.0).

**Comment by limzykenneth** [comment]
@kuhe This still does not seem to be working, though I am getting a different error now:

```
ReferenceError: FileReader is not defined
  Deserialization error: to see the raw response, inspect the hidden field {error}.$response on this object.
    at t3 (/tmp/tmp-157240-Le6BggT4YM6F/worker.js:7397:16)
    at new Promise (<anonymous>)
    at o (/tmp/tmp-157240-Le6BggT4YM6F/worker.js:7396:20)
    at Object.n2 [as streamCollector] (/tmp/tmp-157240-Le6BggT4YM6F/worker.js:7394:70)
    at dd (/tmp/tmp-157240-Le6BggT4YM6F/worker.js:6011:434)
    at tS (/tmp/tmp-157240-Le6BggT4YM6F/worker.js:3486:18)
    at deserialize (/tmp/tmp-157240-Le6BggT4YM6F/worker.js:2575:43)
    at /tmp/tmp-157240-Le6BggT4YM6F/worker.js:8120:21
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /tmp/tmp-157240-Le6BggT4YM6F/worker.js:8179:160 {
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
```

**Comment by kuhe** [comment]
FileReader is a browser native class. If it's not available in the cloudflare environment, try supplying a polyfill for it in your application bundle.

**Comment by trivikr** [comment]
> A fix was released in [v3.329.0](https://github.com/aws/aws-sdk-js-v3/releases/tag/v3.329.0).

Resolving as fix was released, and verified.

**Comment by trivikr** [comment]
> This still does not seem to be working, though I am getting a different error now:
> 
> ```
> ReferenceError: FileReader is not defined
> ```

@limzykenneth Can you create a new [bug report](https://github.com/aws/aws-sdk-js-v3/issues/new?assignees=&labels=bug%2Cneeds-triage&projects=&template=bug-report.yml&title=TITLE+FOR+BUG+REPORT)?

Not that we do not have support for Workers JavaScript runtime.
The issue will be prioritized if it's reproducible in supported browsers
