### ISSUE TITLE
Unable to resolve module @aws-sdk/chunked-blob-reader when using S3Client

### ISSUE THREAD

**Issue by coofzilla** [aws/aws-sdk-js-v3#4631]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

Xcode 14.2
Build version 14C18

ProductName:            macOS
ProductVersion:         13.2.1
BuildVersion:           22D68

I am trying to use the `S3Client` from the `@aws-sdk/client-s3` package in my React Native project, but I am encountering an error related to a missing dependency: `@aws-sdk/chunked-blob-reader`. Can someone help me resolve this issue or let me know what I'm missing?

```
Error: Unable to resolve module @aws-sdk/chunked-blob-reader 
```

`package.json`:

```json
{
  "name": "AmazonExample",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "react": "18.2.0",
    "react-native": "0.71.6",
    "@aws-sdk/client-cognito-identity": "^3.18.0",
    "@aws-sdk/client-s3": "^3.18.0",
    "@aws-sdk/credential-provider-cognito-identity": "^3.18.0",
    "react-native-get-random-values": "^1.6.0",
    "react-native-url-polyfill": "^1.3.0",
    "uuid": "^3.4.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native-community/eslint-config": "^3.2.0",
    "@tsconfig/react-native": "^2.0.2",
    "@types/jest": "^29.2.1",
    "@types/react": "^18.0.24",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.73.9",
    "prettier": "^2.4.1",
    "react-test-renderer": "18.2.0",
    "typescript": "4.8.4"
  },
  "jest": {
    "preset": "react-native"
  }
}

  ```
  
  Additionally, I checked that I _do_ have the required dependency.
  
  ```
  ➜  AmazonExample yarn list --pattern @aws-sdk/chunked-blob-reader
yarn list v1.22.19
└─ @aws-sdk/chunked-blob-reader@3.310.0
✨  Done in 0.22s.
```

```
yarn list v1.22.19
├─ @aws-sdk/abort-controller@3.310.0
├─ @aws-sdk/chunked-blob-reader@3.310.0
├─ @aws-sdk/client-cognito-identity@3.310.0
├─ @aws-sdk/client-s3@3.310.0
├─ @aws-sdk/client-sso-oidc@3.310.0
├─ @aws-sdk/client-sso@3.310.0
├─ @aws-sdk/client-sts@3.310.0
├─ @aws-sdk/config-resolver@3.310.0
├─ @aws-sdk/credential-provider-cognito-identity@3.310.0
├─ @aws-sdk/credential-provider-env@3.310.0
├─ @aws-sdk/credential-provider-imds@3.310.0
├─ @aws-sdk/credential-provider-ini@3.310.0
├─ @aws-sdk/credential-provider-node@3.310.0
├─ @aws-sdk/credential-provider-process@3.310.0
├─ @aws-sdk/credential-provider-sso@3.310.0
├─ @aws-sdk/credential-provider-web-identity@3.310.0
├─ @aws-sdk/eventstream-codec@3.310.0
├─ @aws-sdk/eventstream-serde-browser@3.310.0
├─ @aws-sdk/eventstream-serde-config-resolver@3.310.0
├─ @aws-sdk/eventstream-serde-node@3.310.0
├─ @aws-sdk/eventstream-serde-universal@3.310.0
├─ @aws-sdk/fetch-http-handler@3.310.0
├─ @aws-sdk/hash-blob-browser@3.310.0
├─ @aws-sdk/hash-node@3.310.0
├─ @aws-sdk/hash-stream-node@3.310.0
├─ @aws-sdk/invalid-dependency@3.310.0
├─ @aws-sdk/is-array-buffer@3.310.0
├─ @aws-sdk/md5-js@3.310.0
├─ @aws-sdk/middleware-bucket-endpoint@3.310.0
├─ @aws-sdk/middleware-content-length@3.310.0
├─ @aws-sdk/middleware-endpoint@3.310.0
├─ @aws-sdk/middleware-expect-continue@3.310.0
├─ @aws-sdk/middleware-flexible-checksums@3.310.0
├─ @aws-sdk/middleware-host-header@3.310.0
├─ @aws-sdk/middleware-location-constraint@3.310.0
├─ @aws-sdk/middleware-logger@3.310.0
├─ @aws-sdk/middleware-recursion-detection@3.310.0
├─ @aws-sdk/middleware-retry@3.310.0
├─ @aws-sdk/middleware-sdk-s3@3.310.0
├─ @aws-sdk/middleware-sdk-sts@3.310.0
├─ @aws-sdk/middleware-serde@3.310.0
├─ @aws-sdk/middleware-signing@3.310.0
├─ @aws-sdk/middleware-ssec@3.310.0
├─ @aws-sdk/middleware-stack@3.310.0
├─ @aws-sdk/middleware-user-agent@3.310.0
├─ @aws-sdk/node-config-provider@3.310.0
├─ @aws-sdk/node-http-handler@3.310.0
├─ @aws-sdk/property-provider@3.310.0
├─ @aws-sdk/protocol-http@3.310.0
├─ @aws-sdk/querystring-builder@3.310.0
├─ @aws-sdk/querystring-parser@3.310.0
├─ @aws-sdk/service-error-classification@3.310.0
├─ @aws-sdk/shared-ini-file-loader@3.310.0
├─ @aws-sdk/signature-v4-multi-region@3.310.0
├─ @aws-sdk/signature-v4@3.310.0
├─ @aws-sdk/smithy-client@3.310.0
├─ @aws-sdk/token-providers@3.310.0
├─ @aws-sdk/types@3.310.0
├─ @aws-sdk/url-parser@3.310.0
├─ @aws-sdk/util-arn-parser@3.310.0
├─ @aws-sdk/util-base64@3.310.0
├─ @aws-sdk/util-body-length-browser@3.310.0
├─ @aws-sdk/util-body-length-node@3.310.0
├─ @aws-sdk/util-buffer-from@3.310.0
├─ @aws-sdk/util-config-provider@3.310.0
├─ @aws-sdk/util-defaults-mode-browser@3.310.0
├─ @aws-sdk/util-defaults-mode-node@3.310.0
├─ @aws-sdk/util-endpoints@3.310.0
├─ @aws-sdk/util-hex-encoding@3.310.0
├─ @aws-sdk/util-locate-window@3.310.0
├─ @aws-sdk/util-middleware@3.310.0
├─ @aws-sdk/util-retry@3.310.0
├─ @aws-sdk/util-stream-browser@3.310.0
├─ @aws-sdk/util-stream-node@3.310.0
├─ @aws-sdk/util-uri-escape@3.310.0
├─ @aws-sdk/util-user-agent-browser@3.310.0
├─ @aws-sdk/util-user-agent-node@3.310.0
├─ @aws-sdk/util-utf8-browser@3.259.0
├─ @aws-sdk/util-utf8@3.310.0
├─ @aws-sdk/util-waiter@3.310.0
└─ @aws-sdk/xml-builder@3.310.0
```

### SDK version number

"@aws-sdk/client-s3": "^3.18.0",

### Which JavaScript Runtime is this issue in?

React Native

### Details of the browser/Node.js/ReactNative version

node -v v16.19.0, "react-native": "0.71.6"

### Reproduction Steps

Steps to reproduce:

1. Create a new React Native project.

2. Install the required AWS SDK packages.
    ```json
        "@aws-sdk/client-cognito-identity": "^3.18.0",
        "@aws-sdk/client-s3": "^3.18.0",
        "@aws-sdk/credential-provider-cognito-identity": "^3.18.0",
    ```

3. Follow the example code provided in the AWS SDK for JavaScript documentation.
https://github.com/awsdocs/aws-doc-sdk-examples/blob/main/javascriptv3/example_code/reactnative/App.js

4. Run the project and error pops up.

### Observed Behavior

When trying to use the S3Client in a React Native project, the application encounters the following error:

```
Error: Unable to resolve module @aws-sdk/chunked-blob-reader from /path/to/project/node_modules/@aws-sdk/hash-blob-browser/dist-cjs/index.js: @aws-sdk/chunked-blob-reader could not be found within the project or in these directories:
  node_modules
  2 | Object.defineProperty(exports, "__esModule", { value: true });
  3 | exports.blobHasher = void 0;
> 4 | const chunked_blob_reader_1 = require("@aws-sdk/chunked-blob-reader");
    |                                        ^
  5 | const blobHasher = async function blobHasher(hashCtor, blob) {
  6 |     const hash = new hashCtor();
  7 |     await (0, chunked_blob_reader_1.blobReader)(blob, (chunk) => {
    at ModuleResolver.resolveDependency (/path/to/project/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:162:15)
    at DependencyGraph.resolveDependency (/path/to/project/node_modules/metro/src/node-haste/DependencyGraph.js:260:43)
    at Object.resolve (/path/to/project/node_modules/metro/src/lib/transformHelpers.js:177:21)
    at Graph._resolveDependencies (/path/to/project/node_modules/metro/src/DeltaBundler/Graph.js:432:35)
    at Graph._processModule (/path/to/project/node_modules/metro/src/DeltaBundler/Graph.js:218:38)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Graph._addDependency (/path/to/project/node_modules/metro/src/DeltaBundler/Graph.js:314:20)
    at async Promise.all (index 16)
    at async Graph._processModule (/path/to/project/node_modules/metro/src/DeltaBundler/Graph.js:263:5)
    at async Graph._addDependency (/path/to/project/node_modules/metro/src/DeltaBundler/Graph.js:314:20)
```

The error occurs even when following the example repository provided in the AWS documentation:

https://github.com/awsdocs/aws-doc-sdk-examples/blob/main/javascriptv3/example_code/reactnative/App.js

### Expected Behavior

I expected the S3Client to be imported and successfully initialized without any Errors. After following the example provided in the AWS documentation, I expected to be able to use the S3Client to upload a blob of video data to an S3 bucket.

### Additional Information/Context

Here is the snippet for my actual use case; however, I was able to observe the error even in a brand new project with no configuration.

```js
const useUploadVideo = () => {
  const { mutate, data, isLoading, isError, isSuccess, reset } = useMutation({
    mutationFn: async ({
      videoUri,
      userKey,
      identityPoolId = "some_ID",
      region = "some_REGION",
      s3Bucket = `some-bucket-name`,
    }: UploadVideoParams) => {
      // Fetch the video file and create a blob
      const response = await fetch(videoUri)
      const blob = await response.blob()

      // Create the S3 key for the video
      const key = `s3.amazonaws.com/somePath/${userKey}/testUpload/`

      // Initialize the S3Client
      // https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/getting-started-react-native.html
      const s3Client = new S3Client({
        region,
        credentials: fromCognitoIdentityPool({
          client: new CognitoIdentityClient({ region }),
          identityPoolId: `${region}:${identityPoolId}`,
        }),
      })

      // Create the PutObjectCommand with the required parameters
      // https://docs.aws.amazon.com/AmazonS3/latest/userguide/upload-objects.html
      const command = new PutObjectCommand({
        Bucket: s3Bucket,
        Key: key,
        Body: blob,
        ContentType: blob.type,
      })

      try {
        // Upload the video to S3
        const s3Result = await s3Client.send(command)
        console.log(s3Result)
        return s3Result
      } catch (err) {
        return console.error(err)
      }
    },
  })

  return { mutate, data, isLoading, isError, isSuccess, reset }
}
```

**Comment by cpyle0819** [comment]
Looks like for RN it's trying to resolve to `@aws-sdk/chunked-blob-reader-native`, but that module isn't present.
<img width="1025" alt="Screenshot 2023-04-12 at 12 32 56 PM" src="https://user-images.githubusercontent.com/2723491/231523206-f8784e34-674b-4988-849d-cc11e4b52aa1.png">
<img width="1045" alt="Screenshot 2023-04-12 at 12 34 14 PM" src="https://user-images.githubusercontent.com/2723491/231523425-8ab019f0-1ffa-4526-9155-9294f4a9ca21.png">

**Comment by cpyle0819** [comment]
When I build a package that has a `browser` entry in package.json, it creates a *.browser module in the outputs.
<img width="883" alt="Screenshot 2023-04-12 at 2 44 53 PM" src="https://user-images.githubusercontent.com/2723491/231555177-99746b8f-9146-4733-9435-92ffbb086689.png">
But when I build a package that has the `react-native` entry, it doesn't output anything different:
<img width="1129" alt="Screenshot 2023-04-12 at 2 45 04 PM" src="https://user-images.githubusercontent.com/2723491/231555369-84676c1d-4441-4fe5-9df2-b9e9fb94f6e4.png">

**Comment by cpyle0819** [comment]
Looks like this was the PR that removed the dep. https://github.com/aws/aws-sdk-js-v3/pull/4571

**Comment by coofzilla** [comment]
> Looks like this was the PR that removed the dep. #4571

I ended up installing these version for now, essentially prior to the removal. And it appears to be working.

    "@aws-sdk/client-cognito-identity": "3.298.0",
    "@aws-sdk/client-s3": "3.298.0",
    "@aws-sdk/credential-provider-cognito-identity": "3.298.0",

**Comment by rveramx** [comment]
> Hello @coofzilla did you manage a solution, bug is still there.

Install @aws-sdk/chunked-blob-reader-native

**Comment by dpyeates** [comment]
Any update on this? Still not able to go any higher than 3.2.298.0. 
Installing @aws-sdk/chunked-blob-reader-native gives me other errors.

**Comment by RanVaknin** [comment]
Hey @cpyle0819,

Thanks for the investigation. I will assign a higher priority for this and try to get this fixed asap.
Ran~

**Comment by RanVaknin** [comment]
Hi @dpyeates @rveramx @Hudson-AmalembaL  @coofzilla , @cpyle0819 ,

We just pushed a fix that reintroduces the missing dependency. 
Can you please test if this solves your issue?

Thanks 👍 ,
Ran~

**Comment by kuhe** [comment]
The fix is in https://github.com/awslabs/smithy-typescript/releases/tag/%40smithy%2Fhash-blob-browser%401.0.2

When updating, ensure that this package version is being used in any lockfiles you may have.

**Comment by dpyeates** [comment]
Still not working.

Using

    "@aws-sdk/client-s3": "^3.370.0",
    "@aws-sdk/s3-request-presigner": "^3.370.0",

I am getting the following error:

/node_modules/@smithy/util-stream/dist-cjs/getAwsChunkedEncodingStream.js: stream could not be found

**Comment by cpyle0819** [comment]
@RanVaknin I'm getting the same error as @dpyeates. Happens when running locally.
