### ISSUE TITLE
AWSSDK V3 S3 Setup: fromInstanceMetadata does not retry on error despite maxRetries set

### ISSUE THREAD

**Issue by WarrenWongCodes** [aws/aws-sdk-js-v3#5073]
### Checkboxes for prior research

- [X] I've gone through [Developer Guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide) and [API reference](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest)
- [X] I've checked [AWS Forums](https://forums.aws.amazon.com) and [StackOverflow](https://stackoverflow.com/questions/tagged/aws-sdk-js).
- [X] I've searched for [previous similar issues](https://github.com/aws/aws-sdk-js-v3/issues) and didn't find any solution.

### Describe the bug

There seems to be an issue with the S3 Client, specifically with credentials while utilzing the aws-credential-provider package in aws-sdk v3.

This problem arised from migrating from sdk v2 to v3.

### SDK version number

@aws-sdk/client-s3": "^3.379.1,  @aws-sdk/credential-provider-imds": "^3.374.0", @aws-sdk/credential-providers": "^3.379.1

### Which JavaScript Runtime is this issue in?

Node.js

### Details of the browser/Node.js/ReactNative version

```Error: pulling file from s3:  {"tryNextLink":true,"name":"ProviderError","$metadata":{"attempts":1,"totalRetryDelay":0}}```

### Reproduction Steps
```js
import { S3Client } from '@aws-sdk/client-s3'
import { fromInstanceMetadata } from '@aws-sdk/credential-providers'

const s3Client = new S3Client({
    apiVersion: 'latest',
    credentials: fromInstanceMetadata({
        timeout: 3000,
        maxRetries: 5
    }),
    region: us-east-1
})

///
public async getSitemap(
        fileName: string
    ): Promise<string> {
        const command = new GetObjectCommand({
            Bucket: this.config.getField('SITEMAP_BUCKET_NAME'),
            Key: `${this.config.getField('SITEMAP_V3_FILES_PATH') as string}/${fileName}`
        })

        try {
            const data = await this.s3.send(command) // ! potential issue here

            if(!data.Body) {
                throw new Error('Error: getSitemap - No data available.')
            } else {
                const dataAsBuf = Buffer.from(data.Body.transformToString())
                const dataStr = dataAsBuf.toString('utf8')

                return dataStr
            }
        } catch (error) {
            console.log('Error: pulling file from s3: ', JSON.stringify(error))
            throw new Error('Reader S3 Handler - sitemap not found')
        }
    }
```
### Observed Behavior

There seems to be an issue with the S3 Client, specifically with credentials from what I know so far.

The error originates from the Reader S3 Handler, “attempting” to .send(command) which is trying to getObject() (v2 syntax). However, unable to pull anything.

- Error message in CWL:
Error: pulling file from s3:  {"tryNextLink":true,"name":"ProviderError","$metadata":{"attempts":1,"totalRetryDelay":0}}

- DD Logs Error:  However, data is undefined due to unable to retrieve object from S3 
POST http://URLHERE => The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined

I am utilizing fromInstanceMetadata from aws-credential-provider package, which from the aws docs seems correct:[@aws-sdk/credential-providers | AWS SDK for JavaScript v3](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/modules/_aws_sdk_credential_providers.html)

Following what others facing similar issues [here](https://github.com/aws/aws-sdk-js-v3/issues/4407), and [here](https://github.com/aws/aws-sdk-js-v3/issues/4867), I attempted to increase the maxRetries to 3 and timeout to 3000, however still recieve same error message of attempts 1, and totalRetryDelay 0.

### Expected Behavior

I should receive objects back from the S3 bucket.

**Comment by RanVaknin** [comment]
Hi @WarrenWongCodes ,

You didn't include your full code, mainly the setup of the S3 client is missing. 

Can you try: 
```js
const client = new S3Client({
    region: "us-east-2",
    credentials: fromInstanceMetadata({
        maxRetries: 10 <-- set retries here
    })
})
```

Thanks,
Ran~

**Comment by RanVaknin** [comment]
Hi @WarrenWongCodes ,

When you are creating / updating  an EC2 instance, you should be able to set an IAM role for it:

<img width="643" alt="image" src="https://github.com/aws/aws-sdk-js-v3/assets/50976344/e219020f-8135-4e1a-9467-8b059c4b93a3">


When you're running SDK code  from an context of an EC2 instance, and when you specify `fromInstanceMetadata` in your client config, the SDK will attempt to retrieve credentials by making a request to the instance metadata endpoint (169.254.169.254/latest/meta-data/) this will be done implicitly for you.

If you have not configured your EC2 instance with a valid IAM role and permissions, the IMDS endpoint wont return credentials, then the SDK will throw a `ProviderError` which subsequently will cause any API calls (like to the s3 service) to fail because of the lack of valid credentials.

To root cause this please make sure you have you EC2 instance setup with the appropriate setup. 
You can read up on it [here](https://docs.aws.amazon.com/sdkref/latest/guide/access-iam-roles-for-ec2.html).

Can you give this a shot and let me know if that helps?
Thanks again,
Ran~

**Comment by RanVaknin** [comment]
Hi @WarrenWongCodes ,

I'm not sure why you are running into issues. You haven't included the import lines in your code so maybe the issue stems from there?

Can you please write a simple file called something like `sample.js` that looks like this:

```js
const { S3Client, ListBucketsCommand } = require("@aws-sdk/client-s3");
const { fromInstanceMetadata } = require("@aws-sdk/credential-provider-imds")

const client = new S3Client({
    credentials: fromInstanceMetadata({
        timeout: 3000,
        maxRetries: 5
    }),
    region: "us-east-1"
})

async function run(){
    try {
        const response = await client.send(new ListBucketsCommand({}))
        console.log(response)
    } catch (err) {
        console.log(err)
    }
}
run()
```

And make sure the role attached to your EC2 instance has the necessary permissions to run `listBuckets`.

And then from your ec2 instance run this program: `node sample.js`

The SDK will make the request to the metadata endpoint to assume the role and get credentials back, then using those credentials it will attempt to do a `listBuckets` call that should be successful.

>I'm currently using elasticsearch: ^15.4.1 , but now I'm wondering if we need to use AWS's @aws-sdk/client-elasticsearch-service when migrating to aws - sdk v3.


Based on this question Im wondering if your imports are incorrect. Because SDK JS v3 is modular, you need to import each client separately. So make sure you have the right pacakage installed: `npm install @aws-sdk/client-s3` and then import it (either with `import` or `require`): `const { S3Client, ListBucketsCommand } = require("@aws-sdk/client-s3");`

Please give our [developer guide](https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/welcome.html) and [README](https://github.com/aws/aws-sdk-js-v3/blob/main/README.md) a read to make sure you understand how v3 works, that might help demystify a few things.

Thanks,
Ran~

**Comment by RanVaknin** [comment]
Hi @WarrenWongCodes,

The credential provider packages all moved to `@smithy` so while we have re-exports making the deprecation transparent, for newer versions you need to explicitly install and import the package directly from the smithy repo. You can read more about the change here.

>What is the difference with the `imds` provider versus just `credential-provider` ? 

`credential-providers` is the overarching package that contains re-exports to all the individual providers. There's no concrete difference.

All the SDKs have something called "the default credential chain" which means that by default, the SDK will run through a list of 5-6 providers and try to obtain credentials. This is done implicitly for you. So if you are running your code from an EC2 instace, you dont need to specify `fromInstanceMetada` at all unless you want to override the default behavior (like configuring the max retry attempts)

I'm still not sure if you are still stuck or you figured it out? If youre still stuck it will be helpful to understand how you are running your code? is it from a docker container, a bare bones EC2 instance, an EKS pod? 

Thanks,
Ran~

**Comment by atif-saddique-deel** [comment]
I think the issue here is not related to retries, but something related to this one probably : https://github.com/aws/aws-sdk-js-v3/issues/4491
We are having the same issue, I have tested the custom retry as well, but it gives the same error even if I retry 10 times for 10 minutes. 
If I terminate the pod, it get's scheduled on a different host and it works. We are using spot instances, not sure if its related.

**Comment by RanVaknin** [comment]
Hi @atif-saddique-deel ,

The error you are seeing is happening because the SDK cannot retrieve credentials from the IMDS endpoint itself. 
My suggestion is, from the failing pod curl the IMDS endpoint directly: `curl http://169.254.169.254/latest/meta-data/
` And see if you are able to call that endpoint. If you are not, there's a connectivity issue between your pod and AWS. 

Im curious to see what you can find.

Thanks,
Ran~

**Comment by RanVaknin** [comment]
Hi @atif-saddique-deel ,

Glad to hear you worked this out. 

@WarrenWongCodes ,
Since I didnt hear back from you I assume this is solved? If you need more help, feel free to open a separate issue. 

Thanks,
Ran~

**Comment by atif-saddique-deel** [comment]
We didn't manage to fix the issue as kube2iam still have issue but I can confirm that the issue is not caused by retries.
