### ISSUE TITLE
The ordering of commands is not consistent in AlexaForBusiness

### ISSUE THREAD

**Issue by trivikr** [aws/aws-sdk-js-v3#781]
**Describe the bug**
The ordering of commands is not consistent in AlexaForBusiness

**To Reproduce (observed behavior)**
* Consistent ordering was introduced in https://github.com/awslabs/smithy-typescript/pull/78
* Ordering was updated for rest-json clients in https://github.com/aws/aws-sdk-js-v3/pull/661
* Note that ordering is not updated for AlexaForBusiness https://github.com/aws/aws-sdk-js-v3/blob/7e4ac4828f8775bde7adfe3f5f247bdb687bfb44/clients/client-alexa-for-business/index.ts#L2-L5
* When codegen was run for alexa-for-business, it didn't sort commands

**Expected behavior**
Consistent ordering is maintained for all clients

**Comment by srchase** [comment]
This issue was resolved via https://github.com/awslabs/smithy-typescript/pull/108

**Comment by trivikr** [comment]
It's not yet resolved as `SendAnnouncementCommand` appears before `DeleteDeviceUsageDataCommand`
https://github.com/aws/aws-sdk-js-v3/blob/80e6356d329151138e144cc75b3abb8a142a83c3/clients/client-alexa-for-business/index.ts#L3-L5

**Comment by srchase** [comment]
This ordering is due to the inclusion of the namespace:

https://github.com/aws/aws-sdk-js-v3/blob/a10e47019abd2e255e72f4462ec67f88b236eab7/models/alexa-for-business.2017-11-09.json#L123-L131

To fix this, the ordering needs to be based only off of the operation name.

**Comment by srchase** [comment]
This ordering is stable and does not need to be changed.  Resolving this issue.
