### ISSUE TITLE
@aws-sdk/util-create-request returns undefined

### ISSUE THREAD

**Issue by Amplifiyer** [aws/aws-sdk-js-v3#788]
**Describe the bug**

**SDK version number** 
@aws-sdk/util-create-request@1.0.0-alpha.7

**Is the issue in the browser/Node.js?**
Browser

**Details of the browser/Node.js version**
```
  Browsers:
    Chrome: 79.0.3945.130
    Safari: 13.0.4
```

**To Reproduce (observed behavior)**
```javascript
import { S3Client } from "@aws-sdk/client-s3-node/S3Client";
import { GetObjectCommand } from "@aws-sdk/client-s3-node/commands/GetObjectCommand";
const request = await createRequest(
  new S3Client({}),
  new GetObjectCommand({
    Bucket: "bucket",
    Key: "key"
  })
console.log(request) // ==> Undefined
);
```
**Expected behavior**
request should not be undefined

**Screenshots**

**Additional context**

**Comment by srchase** [comment]
@Amplifiyer 

Is this the correct code to reproduce?  This is using the old node/browser specific client import.

I'd expect your import to look like this instead:

```
import { S3Client, GetObjectCommand } from "@aws-sdk/clients/client-s3"
```

**Comment by trivikr** [comment]
The fix was released in v1.0.0-alpha.8 https://www.npmjs.com/package/@aws-sdk/util-create-request/v/1.0.0-alpha.8

@Amplifiyer Can you verify if it's fixed?

**Comment by Amplifiyer** [comment]
It's not returning undefined anymore. However our tests are still failing and it seems that the bucket parameter is missing in the request.path. I'll try to test it in a real application and update here.

**Comment by trivikr** [comment]
Resolving as this particular issue is resolved.
Let's discuss bucket parameter missing in request.path in [new issue](https://github.com/aws/aws-sdk-js-v3/issues/new?assignees=&labels=bug+report&template=---bug-report.md&title=)
